[build-system]
requires = ["setuptools >= 61.0.0.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.setuptools.package-data]
"tfi.data" = ["py.typed"]
