#docker-compose up --build
#docker-compose -f docker-compose-example.yml up --build

services:
  ingestor_one:
      build: ../.
      command: python3 src/truflation/data/pipeline_coupler.py examples/csv_example/my_pipeline_details.py
      volumes:
        - pipeline_details:/data/todo
  ingestor_two:
      build: ../.
      command: python3 src/truflation/data/pipeline_coupler.py examples/csv_example/my_pipeline_details.py
      volumes:
        - pipeline_details:/data/todo
  investing:
      build: ../.
      command: examples/investing/load_data.py
      volumes:
        - pipeline_details:/data/todo

volumes:
  pipeline_details:
    driver: local
